package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/martinhrvn/paleta/internal/config"
	"github.com/martinhrvn/paleta/internal/scan"
	"github.com/martinhrvn/paleta/internal/ui"
	"gopkg.in/yaml.v3"
)

// InitOutcome describes the result of running the interactive init wizard.
type InitOutcome int

const (
	InitWritten         InitOutcome = iota // a new .pltrc was written
	InitNoProjects                         // nothing detected in the tree
	InitCanceled                           // user aborted the wizard
	InitNothingSelected                    // wizard confirmed with no locations
)

// RunInitWizard scans the current directory, lets the user pick which projects
// to include, and writes the resulting .pltrc, preserving any existing config as
// the starting state. It performs no stdout output, so it is safe to call from
// within `plt select` (whose stdout carries the selection JSON). Callers decide
// how to report the returned outcome.
func RunInitWizard(configPath string) (InitOutcome, error) {
	cands, err := scan.Scan(".")
	if err != nil {
		return InitNoProjects, fmt.Errorf("scanning for projects: %w", err)
	}

	authored, err := LoadAuthoredConfig(configPath)
	if err != nil {
		return InitNoProjects, fmt.Errorf("reading existing config: %w", err)
	}

	items := BuildWizardItems(cands, authored)
	if len(items) == 0 {
		return InitNoProjects, nil
	}

	wizard := ui.NewWizardModel(items)
	locations, confirmed, err := wizard.Run()
	if err != nil {
		return InitCanceled, fmt.Errorf("running wizard: %w", err)
	}
	if !confirmed {
		return InitCanceled, nil
	}
	if len(locations) == 0 {
		return InitNothingSelected, nil
	}

	content := GenerateConfig(locations, authored)
	if err := WriteConfig(configPath, content); err != nil {
		return InitWritten, fmt.Errorf("writing config: %w", err)
	}
	return InitWritten, nil
}

// LoadAuthoredConfig reads an existing .pltrc as authored, without the path
// resolution, glob expansion, or project-type processing that config.LoadConfig
// applies. This preserves relative paths, globs, and hand-written commands so a
// repeat run of the wizard can round-trip them. Returns (nil, nil) when the file
// does not exist.
func LoadAuthoredConfig(configPath string) (*config.Config, error) {
	data, err := os.ReadFile(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	var cfg config.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse config file: %w", err)
	}
	return &cfg, nil
}

// BuildWizardItems unions scan candidates with the locations from an existing
// config (authored may be nil). Authored locations come first and are preserved
// verbatim; a candidate matching an authored location by path marks it Detected,
// while remaining candidates are appended as newly detected items.
func BuildWizardItems(cands []scan.Candidate, authored *config.Config) []ui.WizardItem {
	var items []ui.WizardItem
	matched := make(map[string]bool) // candidate RelPath already represented

	if authored != nil {
		for _, loc := range authored.Locations {
			item := ui.WizardItem{Location: loc, Configured: true}
			cleaned := filepath.Clean(loc.Location)
			for _, c := range cands {
				if c.RelPath == cleaned {
					item.Detected = true
					matched[c.RelPath] = true
					break
				}
			}
			items = append(items, item)
		}
	}

	for _, c := range cands {
		if matched[c.RelPath] {
			continue
		}
		items = append(items, ui.WizardItem{
			Location: config.Location{
				Name:     locationName(c.RelPath),
				Location: c.RelPath,
				Types:    c.Types,
			},
			Detected: true,
		})
	}

	return items
}

// locationName derives a display name from a relative path. The scan root (".")
// becomes "root"; otherwise the base directory name is used.
func locationName(relPath string) string {
	if relPath == "." || relPath == "" {
		return "root"
	}
	return filepath.Base(relPath)
}

// generatedHeader is prepended to wizard-generated .pltrc files.
const generatedHeader = `# paleta configuration file
# Generated by 'plt init'. Edit freely or re-run 'plt init' to update.
`

// generatedConfig is the YAML shape emitted by the wizard. Frecency is a pointer
// so it is only written when carried over from an existing config.
type generatedConfig struct {
	Frecency  *config.FrecencyConfig `yaml:"frecency,omitempty"`
	Locations []config.Location      `yaml:"locations"`
}

// GenerateConfig renders the selected locations as .pltrc YAML. When preserved
// is non-nil and carries a frecency block, that block is written back so a
// repeat run never drops the user's settings.
func GenerateConfig(locations []config.Location, preserved *config.Config) string {
	out := generatedConfig{Locations: locations}
	if preserved != nil && hasFrecency(preserved.Frecency) {
		fr := preserved.Frecency
		out.Frecency = &fr
	}

	data, err := yaml.Marshal(out)
	if err != nil {
		// yaml.Marshal of these plain structs cannot realistically fail; fall
		// back to just the header so we never panic in the CLI path.
		return generatedHeader
	}
	return generatedHeader + string(data)
}

// hasFrecency reports whether a frecency block carries explicit settings worth
// preserving (as opposed to the zero value of an absent block).
func hasFrecency(fr config.FrecencyConfig) bool {
	return fr.Enabled || fr.RecencyWeight != 0 || fr.FrequencyWeight != 0
}

// WriteConfig writes content to configPath, overwriting any existing file.
func WriteConfig(configPath, content string) error {
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}
	return nil
}

// DefaultConfigTemplate returns the default .pltrc template
func DefaultConfigTemplate() string {
	return `# paleta configuration file
# This file defines locations and commands for your project

locations:
  # Example: NPM/Yarn/PNPM project with automatic script detection
  - name: "frontend"
    location: "packages/frontend"
    type: "npm"  # Automatically discovers package.json scripts
    commands:
      # Additional custom commands beyond package.json scripts
      - "npm run dev"

  # Example: Backend service with manual commands
  - name: "backend"
    location: "packages/backend"
    commands:
      - "npm start"
      - "npm test"
      - "npm run build"

  # Example: A folder that is both an npm package and a Docker service.
  # Commands from every type are merged; each is labelled with its type, e.g.
  # "svc: [npm] build" and "svc: [docker] build".
  # - name: "svc"
  #   location: "services/svc"
  #   type: [npm, docker]

  # Example: Filtering auto-discovered commands with include/exclude
  # - name: "app"
  #   location: "app"
  #   type: "npm"
  #   include:           # Only include commands matching these patterns
  #     - "npm run dev"
  #     - "npm run build*"
  #     - "npm run test"
  #   exclude:           # Exclude commands matching these patterns
  #     - "npm run test:watch"
  #   commands:
  #     - "custom-command"

  # Example: Using glob patterns to match multiple directories
  # - location: "packages/*"
  #   type: "npm"

  # Example: Scripts directory with shell scripts
  # - name: "scripts"
  #   location: "scripts"
  #   commands:
  #     - "./deploy.sh"
  #     - "./backup.sh"

# Configuration reference:
#
# location fields:
#   name:     (optional) Display name shown in selection UI
#   location: (optional) Path to project directory (supports glob patterns like "packages/*")
#                        If omitted, defaults to current directory "."
#   type:     (optional) Project type(s) for automatic command detection.
#             Single value (type: npm) or a list (type: [npm, docker]).
#   commands: (optional) List of commands to make available
#   include:  (optional) Glob patterns to filter auto-discovered commands (whitelist)
#   exclude:  (optional) Glob patterns to exclude from auto-discovered commands (blacklist)
#
# include/exclude notes:
#   - Only applies to auto-discovered commands (from type), not manual commands
#   - Patterns support glob syntax (e.g., "npm run test*" matches "npm run test:ci")
#   - Include is applied first (whitelist), then exclude (blacklist)
#   - Commands must match the format shown in the UI (e.g., "npm run dev", not "dev")
#
# Supported project types:
#   npm, yarn, pnpm: Automatically discovers scripts from package.json
#   go: Discovers standard Go commands (planned)
#
# For more information, see: https://github.com/martinhrvn/paleta
`
}

// CreateDefaultConfig creates a default .pltrc file at the specified path
// Returns an error if the file already exists
func CreateDefaultConfig(configPath string) error {
	return CreateDefaultConfigWithForce(configPath, false)
}

// CreateDefaultConfigWithForce creates a default .pltrc file at the specified path
// If force is true, overwrites existing file
func CreateDefaultConfigWithForce(configPath string, force bool) error {
	// Check if file already exists
	if _, err := os.Stat(configPath); err == nil {
		if !force {
			return fmt.Errorf("config file already exists at %s (use --force to overwrite)", configPath)
		}
	}

	// Create the file with default template
	content := DefaultConfigTemplate()
	err := os.WriteFile(configPath, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}
