package config

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"

	"gopkg.in/yaml.v3"
)

// generatedHeader heads a .pltrc that plt wrote from scratch.
const generatedHeader = "# paleta configuration file\n# Generated by 'plt init'. Edit freely or re-run 'plt init' to update."

// deprecatedKeys maps each superseded location key to its current spelling.
// Location.UnmarshalYAML still accepts the old ones; every rewrite emits the new.
var deprecatedKeys = []struct{ old, new string }{
	{"include", "include_commands"},
	{"exclude", "exclude_commands"},
}

// locationKeys lists every key a location entry may carry (see locationYAML), so
// a rewrite knows which keys it owns. Anything else in the entry is left alone.
var locationKeys = []string{
	"name", "location", "type", "commands", "include_commands", "exclude_commands",
	"include", "exclude", "exclude_locations", "overrides", "env",
}

// NameFix records one repair made by File.Fix.
type NameFix struct {
	Scope  string // "location", "command", or "key" (a deprecated key renamed)
	Before string
	After  string
}

// File is an authored .pltrc opened for editing in place. Every rewrite plt
// performs — `plt init` merging, a focus save, a queue save, `plt lint --fix` —
// goes through it, and each edit touches only the nodes it is about, so
// comments, key order and keys plt doesn't manage survive a Save. It is the one
// place that turns Config values back into YAML.
type File struct {
	path string
	doc  *yaml.Node // DocumentNode whose Content[0] is the top-level mapping
	perm os.FileMode
}

// OpenFile reads the .pltrc at path for editing. A missing file is reported with
// an error satisfying errors.Is(err, fs.ErrNotExist); one that can't be read or
// parsed with an *InvalidConfigError naming it.
func OpenFile(path string) (*File, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
		return nil, &InvalidConfigError{Path: absOrSelf(path), Err: err}
	}
	perm := os.FileMode(0644)
	if info, err := os.Stat(path); err == nil {
		perm = info.Mode().Perm()
	}

	f := &File{path: path, doc: &yaml.Node{}, perm: perm}
	if err := yaml.Unmarshal(data, f.doc); err != nil {
		return nil, &InvalidConfigError{Path: absOrSelf(path), Err: err}
	}
	f.ensureRoot()
	// A file that isn't config-shaped at all (a bare list, say) is rejected now
	// rather than from the middle of an edit.
	if _, err := f.Authored(); err != nil {
		return nil, &InvalidConfigError{Path: absOrSelf(path), Err: err}
	}
	return f, nil
}

// NewFile starts an empty .pltrc at path, headed by the generated-file comment.
// Nothing is written until Save.
func NewFile(path string) *File {
	f := &File{path: path, doc: &yaml.Node{}, perm: 0644}
	f.ensureRoot()
	f.doc.HeadComment = generatedHeader
	return f
}

// LoadAuthored reads the .pltrc at path as authored — relative paths, globs and
// commands exactly as written, with none of the resolution a load performs.
// Returns (nil, nil) when there is no such file.
func LoadAuthored(path string) (*Config, error) {
	f, err := OpenFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return f.Authored()
}

// Authored decodes the file's current content as a Config, in its authored form.
func (f *File) Authored() (*Config, error) {
	var cfg Config
	if err := f.doc.Decode(&cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// SetFocused replaces the top-level focus list; an empty list removes the key.
func (f *File) SetFocused(keys []string) error {
	root, err := f.root()
	if err != nil {
		return err
	}
	if len(keys) == 0 {
		deleteMapKey(root, "focused")
		return nil
	}
	node, err := encodeNode(keys)
	if err != nil {
		return err
	}
	setMapValue(root, "focused", node)
	return nil
}

// SetLocations rewrites the location list to locs, in that order. A location
// already in the file (matched by path) keeps its authored entry — comments and
// all — with only the fields that changed replaced; entries left out are
// dropped and new ones appended. Nothing outside `locations:` is touched.
func (f *File) SetLocations(locs []Location) error {
	seq, err := f.locations()
	if err != nil {
		return err
	}

	existing := make(map[string]*yaml.Node, len(seq.Content))
	for _, n := range seq.Content {
		if n.Kind != yaml.MappingNode {
			continue
		}
		key := locationKey(scalarValue(mapValue(n, "location")))
		if _, dup := existing[key]; !dup {
			existing[key] = n
		}
	}

	content := make([]*yaml.Node, 0, len(locs))
	for _, loc := range locs {
		fresh, err := encodeNode(loc)
		if err != nil {
			return err
		}
		key := locationKey(loc.Location)
		if n, ok := existing[key]; ok {
			delete(existing, key)
			mergeLocation(n, fresh)
			content = append(content, n)
			continue
		}
		content = append(content, fresh)
	}
	seq.Content = content
	return nil
}

// AppendCommand adds cmd to the end of the index-th location's command list,
// creating the list when the location has none.
func (f *File) AppendCommand(index int, cmd Command) error {
	seq, err := f.locations()
	if err != nil {
		return err
	}
	if index < 0 || index >= len(seq.Content) || seq.Content[index].Kind != yaml.MappingNode {
		return fmt.Errorf("no location at index %d", index)
	}
	loc := seq.Content[index]

	cmds := mapValue(loc, "commands")
	if cmds == nil || cmds.Kind != yaml.SequenceNode {
		cmds = &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		setMapValue(loc, "commands", cmds)
	}
	node, err := encodeNode(cmd)
	if err != nil {
		return err
	}
	cmds.Content = append(cmds.Content, node)
	return nil
}

// AddLocation appends loc to the location list.
func (f *File) AddLocation(loc Location) error {
	seq, err := f.locations()
	if err != nil {
		return err
	}
	node, err := encodeNode(loc)
	if err != nil {
		return err
	}
	seq.Content = append(seq.Content, node)
	return nil
}

// Fix repairs what `plt lint --fix` can: names outside the alias-safe charset
// have their offending characters replaced with '_' (see SanitizeName), and
// deprecated keys — on locations and on each entry under `overrides:` — are
// renamed to their current spellings. Returns the repairs made, in file order.
func (f *File) Fix() []NameFix {
	root, err := f.root()
	if err != nil {
		return nil
	}
	locs := mapValue(root, "locations")
	if locs == nil || locs.Kind != yaml.SequenceNode {
		return nil
	}

	var fixes []NameFix
	for _, loc := range locs.Content {
		if before, after, ok := fixNameNode(mapValue(loc, "name"), false); ok {
			fixes = append(fixes, NameFix{Scope: "location", Before: before, After: after})
		}
		fixes = append(fixes, renameDeprecatedKeys(loc)...)
		cmds := mapValue(loc, "commands")
		if cmds == nil || cmds.Kind != yaml.SequenceNode {
			continue
		}
		for _, cmd := range cmds.Content {
			if before, after, ok := fixNameNode(mapValue(cmd, "name"), true); ok {
				fixes = append(fixes, NameFix{Scope: "command", Before: before, After: after})
			}
		}
	}
	return fixes
}

// Bytes renders the file as it would be saved. Deprecated keys are upgraded on
// the way out, so every rewrite emits the current spellings.
func (f *File) Bytes() ([]byte, error) {
	if root, err := f.root(); err == nil {
		if locs := mapValue(root, "locations"); locs != nil && locs.Kind == yaml.SequenceNode {
			for _, loc := range locs.Content {
				renameDeprecatedKeys(loc)
			}
		}
	}

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(f.doc); err != nil {
		return nil, fmt.Errorf("failed to render config: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("failed to render config: %w", err)
	}
	return buf.Bytes(), nil
}

// Save writes the file back, keeping its original permissions.
func (f *File) Save() error {
	data, err := f.Bytes()
	if err != nil {
		return err
	}
	if err := os.WriteFile(f.path, data, f.perm); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}
	return nil
}

// ensureRoot gives an empty or comment-only document a top-level mapping.
func (f *File) ensureRoot() {
	if f.doc.Kind != yaml.DocumentNode {
		*f.doc = yaml.Node{Kind: yaml.DocumentNode}
	}
	if len(f.doc.Content) == 0 || (f.doc.Content[0].Kind == yaml.ScalarNode && f.doc.Content[0].Tag == "!!null") {
		f.doc.Content = []*yaml.Node{{Kind: yaml.MappingNode, Tag: "!!map"}}
	}
}

// root returns the top-level mapping.
func (f *File) root() (*yaml.Node, error) {
	n := f.doc.Content[0]
	if n.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("config is not a mapping")
	}
	return n, nil
}

// locations returns the `locations:` sequence, creating it when absent.
func (f *File) locations() (*yaml.Node, error) {
	root, err := f.root()
	if err != nil {
		return nil, err
	}
	seq := mapValue(root, "locations")
	if seq == nil || seq.Kind != yaml.SequenceNode {
		seq = &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		setMapValue(root, "locations", seq)
	}
	return seq, nil
}

// locationKey identifies a location entry by its path; an absent path is ".".
func locationKey(path string) string {
	return filepath.Clean(path)
}

// mergeLocation makes the authored entry dst carry the same fields as fresh (a
// freshly encoded Location): a field whose value is unchanged keeps its node and
// comments, a changed one takes the new node, a field fresh lacks is removed.
// Keys plt doesn't own are left alone.
func mergeLocation(dst, fresh *yaml.Node) {
	renameDeprecatedKeys(dst) // so an unchanged filter compares equal under its new name
	for i := 0; i+1 < len(fresh.Content); i += 2 {
		key, val := fresh.Content[i].Value, fresh.Content[i+1]
		if cur := mapValue(dst, key); cur != nil && fieldsEqual(key, cur, val) {
			continue
		}
		setMapValue(dst, key, val)
	}
	for _, key := range locationKeys {
		if mapValue(fresh, key) == nil {
			deleteMapKey(dst, key)
		}
	}
}

// fieldsEqual reports whether two value nodes for a location key mean the same
// thing, by decoding each as that field of a Location — so `- pnpm dev` and
// `- command: pnpm dev` compare equal, as do a scalar and a one-item type list.
func fieldsEqual(key string, a, b *yaml.Node) bool {
	decode := func(val *yaml.Node) (Location, error) {
		wrapped := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, val,
		}}
		var loc Location
		err := wrapped.Decode(&loc)
		return loc, err
	}
	la, errA := decode(a)
	lb, errB := decode(b)
	return errA == nil && errB == nil && reflect.DeepEqual(la, lb)
}

// encodeNode renders v as a YAML node (through any MarshalYAML it defines).
func encodeNode(v any) (*yaml.Node, error) {
	var n yaml.Node
	if err := n.Encode(v); err != nil {
		return nil, fmt.Errorf("failed to render config: %w", err)
	}
	return &n, nil
}

func scalarValue(n *yaml.Node) string {
	if n == nil {
		return ""
	}
	return n.Value
}

// mapValue returns the value node for key in a mapping node, or nil.
func mapValue(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

// setMapValue replaces key's value in a mapping node (keeping the key node and
// its comments), or appends the pair when the key is absent.
func setMapValue(m *yaml.Node, key string, val *yaml.Node) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			m.Content[i+1] = val
			return
		}
	}
	m.Content = append(m.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, val)
}

// deleteMapKey removes key and its value from a mapping node.
func deleteMapKey(m *yaml.Node, key string) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			m.Content = append(m.Content[:i], m.Content[i+2:]...)
			return
		}
	}
}

// fixNameNode sanitizes a scalar name node in place, reporting whether it
// changed. A nil or non-scalar node is a no-op.
func fixNameNode(node *yaml.Node, isCommand bool) (before, after string, changed bool) {
	if node == nil || node.Kind != yaml.ScalarNode {
		return "", "", false
	}
	fixed := SanitizeName(node.Value, isCommand)
	if fixed == node.Value {
		return "", "", false
	}
	before = node.Value
	node.Value = fixed
	node.Tag = "!!str"
	node.Style = 0 // let the emitter pick quoting for the new value
	return before, fixed, true
}

// renameDeprecatedKeys rewrites the deprecated filter keys of a location entry
// and of each folder entry under its `overrides:` to their current spellings,
// reporting each rename.
func renameDeprecatedKeys(loc *yaml.Node) []NameFix {
	var fixes []NameFix
	rename := func(m *yaml.Node) {
		for _, k := range deprecatedKeys {
			if renameKeyNode(m, k.old, k.new) {
				fixes = append(fixes, NameFix{Scope: "key", Before: k.old, After: k.new})
			}
		}
	}
	rename(loc)
	if overrides := mapValue(loc, "overrides"); overrides != nil && overrides.Kind == yaml.MappingNode {
		for i := 1; i < len(overrides.Content); i += 2 {
			rename(overrides.Content[i])
		}
	}
	return fixes
}

// renameKeyNode renames a mapping key in place, reporting whether it changed. The
// key node is mutated rather than replaced so its comments survive. A mapping that
// already carries the new key is left alone: merging two authored keys is the
// user's call, so lint keeps warning instead.
func renameKeyNode(m *yaml.Node, old, new string) bool {
	if m == nil || m.Kind != yaml.MappingNode {
		return false
	}
	if mapValue(m, new) != nil {
		return false
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == old {
			m.Content[i].Value = new
			return true
		}
	}
	return false
}
